#!/bin/sh
COLLECT_VIDEOS_DIR="/config/collect_videos"
RECORDINGS_DIR=$1
RECORDINGS=`ls $RECORDINGS_DIR/*.mp4`
RECORDINGS=`basename $RECORDINGS`
#FOLDER_NAME=$(echo $RECORDINGS | tr "_" "\n")
FOLDER_NAME=$(echo $RECORDINGS |cut -d '_' -f1)
#FILE_NAME=$(basename $(ls $RECORDINGS_DIR/*.mp4))
FILE_NAME=$(echo $RECORDINGS |cut -d '_' -f2)
echo "RECORDINGS_DIR=$RECORDINGS_DIR RECORDINGS=$RECORDINGS  FOLDER_NAME=$FOLDER_NAME FILE_NAME=$FILE_NAME" >>/config/collect_videos/finalize.out.txt

mkdir -p $COLLECT_VIDEOS_DIR/$FOLDER_NAME;
cp -ap $RECORDINGS_DIR/$RECORDINGS $COLLECT_VIDEOS_DIR/$FOLDER_NAME/$FILE_NAME
