<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "sm_teachers_disciplines".
 *
 * @property int $discipline_id
 * @property int $teacher_user_id
 */
class TeachersDisciplines extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'sm_teachers_disciplines';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['discipline_id', 'teacher_user_id'], 'required'],
            //[['discipline_id', 'teacher_user_id'], 'default', 'value' => null],
            [['discipline_id', 'teacher_user_id'], 'integer'],
            [['discipline_id', 'teacher_user_id'], 'unique', 'targetAttribute' => ['discipline_id', 'teacher_user_id']],
            [['discipline_id'], 'exist', 'skipOnError' => true, 'targetClass' => Disciplines::className(), 'targetAttribute' => ['discipline_id' => 'discipline_id']],
            [['teacher_user_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['teacher_user_id' => 'user_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'discipline_id' => 'Discipline ID',
            'teacher_user_id' => 'Teacher User ID',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function afterDelete()
    {
        parent::afterDelete();
        $User = Users::findIdentity($this->teacher_user_id);
        $User->teacher_profile_completed = Users::NO;
        $User->save();
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if ($this->isNewRecord) {
            $User = Users::findIdentity($this->teacher_user_id);
            $User->teacher_profile_completed = Users::NO;
            $User->save();
        }
    }
}
